AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  memorize

  Sample SAM Template for memorize

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10


Resources:

  HandleMemos:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: memos/
      Handler: memos
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /memos
            Method: POST
            RequestParameters:
                "method.request.querystring.memo-type":
                  Required: false
                  Caching: false
      Environment:
        Variables:
          PARAM1: VALUE

  HandleMemo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: memos/
      Handler: memos
      Runtime: go1.x
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /memos/{pk}
            Method: ANY
      Environment:
        Variables:
          PARAM1: VALUE

  HandleSettings:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: settings/
      Handler: settings
      Runtime: go1.x
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /settings
            Method: POST
      Environment:
        Variables:
          PARAM1: VALUE

  SendNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notifications/
      Handler: notifications
      Runtime: go1.x
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess # need to change (Read Only)
      Environment:
        Variables:
          LAMBDA_ENV_TYPE: prod
          SlackWebhookURl: https://hooks.slack.com/services/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


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    HelloWorldAPI:
      Description: "API Gateway endpoint URL for Prod environment for First Function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

